name: Build

on:
  push:
    branches:
      [main, developing]
  pull_request:
    branches:
      - '*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - uses: actions/checkout@v2.4.0
        name: Checkout
      - run: sudo apt-get update
        name: Update packages list
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - uses: jurplel/install-qt-action@v2.14.0
        name: Install Qt
        with:
          version: '5.15.2'
          archives: qtmultimedia qtwebsockets
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          aqtversion: '==2.0.6'
          install-deps: true
      - run: sudo apt-get install protobuf-compiler
        name: Install Protobuf
      - run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_C_COMPILER=gcc-11
        name: Configure CMake
      - run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2
        name: Build project
